Phala-Network/khala-parachain

- node/src/cli.rs
- node/src/command.rs
- scripts/export-parachain-genesis.sh
Allow customize parachain id by adding a prefix to the chain name.
It only applies to "khala-dev" and "khala-local".
E.g.:"khala-local-2004" means "khala-local" at para 2004
> Custom parachain id in chain name 

- runtime/khala/src/lib.rs
I forgot port https://github.com/paritytech/cumulus/pull/538 when we upgrade to 0.9.8
> Port paritytech/cumulus/pull/538

- pallets/xtransfer/src/assets_wrapper.rs
- pallets/xtransfer/src/bridge/mock.rs
- pallets/xtransfer/src/bridge/mod.rs
- pallets/xtransfer/src/bridge/tests.rs
- pallets/xtransfer/src/bridge_transfer/mock.rs
- pallets/xtransfer/src/bridge_transfer/mod.rs
- pallets/xtransfer/src/bridge_transfer/tests.rs
- pallets/xtransfer/src/xcm/xcm_helper.rs
- pallets/xtransfer/src/xcm/xcm_transfer.rs
- runtime/khala/src/lib.rs
- runtime/rhala/src/lib.rs
- runtime/thala/src/lib.rs
- scripts/js/xtransfer.js
- Remove resource id store in pallet-bridge
Previously we set a constant resource id for PHA, that because it just need match the rid configed in Ethereum,
now different solo chain have different resource id, even though they are both indicate PHA. So there is no need
store resource id in pallet-bridge any more, instead we compute it dynamically during transfer.
Dispatch `set_resource` and other resource setting relevant methods are removed too, including ChainBridge relayer side.
- Fix PHA resource id computation
Fix PHA resource id computation in `BridgeTransfer.transfer` and `XcmTransactor.deposit_asset` which would case PHA transfer with other solo chains except Ethereum(with chain id 0) failure.
> Fix PHA resource id computation

- pallets/xtransfer/src/assets_wrapper.rs
- pallets/xtransfer/src/bridge_transfer/mock.rs
- pallets/xtransfer/src/bridge_transfer/mod.rs
- pallets/xtransfer/src/bridge_transfer/tests.rs
- pallets/xtransfer/src/xcm/mock/para.rs
- pallets/xtransfer/src/xcm/xcm_helper.rs
- pallets/xtransfer/src/xcm/xcm_transfer.rs
- runtime/khala/src/constants.rs
- runtime/khala/src/lib.rs
- runtime/rhala/src/constants.rs
- runtime/rhala/src/lib.rs
- runtime/thala/src/constants.rs
- runtime/thala/src/lib.rs
- Deduct fee when forwarding assets to solo chain.
- Pay asset itself as fee rather than PHA when transfering non-native assets to solo chains.
- Extra events added in xcm-transfer pallet.
- More information on chainbridge registry struct
> xTransfer update

- pallets/xtransfer/src/assets_wrapper.rs
- pallets/xtransfer/src/bridge_transfer/mock.rs
- pallets/xtransfer/src/bridge_transfer/mod.rs
- pallets/xtransfer/src/bridge_transfer/tests.rs
- pallets/xtransfer/src/xcm/xcm_helper.rs
- pallets/xtransfer/src/xcm/xcm_transfer.rs
- runtime/khala/src/lib.rs
- runtime/thala/src/lib.rs
- scripts/js/package.json
- scripts/js/xtransfer_fee.js
- scripts/js/xtransfer_index.js
- scripts/js/yarn.lock
- Add struct AssetProperties in AssetRegistryInfo
- Set metadata when register assets
- Return proper fee amount when decimals of asset if not 12
> Asset wrapper and fee updates

- pallets/xtransfer/src/xcm/xcm_transfer.rs
Note set whole asset amount as fee is the most effective way  to avoid insufficient fee payment on destination, we can do like this because XCM only deducte amount that spend by the execution, the rest of the fee will be deposited to recipient amount. It's more properly to estimate the fee when decimals, price and fee/ED configuration of the asset known on destination.
> Use whole asset amount as fee

- Cargo.lock
- Cargo.toml
- pallets/phala-world/Cargo.toml
- pallets/phala-world/README.md
- pallets/phala-world/src/incubation.rs
- pallets/phala-world/src/lib.rs
- pallets/phala-world/src/mock.rs
- pallets/phala-world/src/nft_sale.rs
- pallets/phala-world/src/tests.rs
- pallets/phala-world/src/traits.rs
- runtime/khala/Cargo.toml
- runtime/khala/src/lib.rs
- runtime/rhala/Cargo.toml
- runtime/rhala/src/lib.rs
- runtime/thala/Cargo.toml
- runtime/thala/src/lib.rs
- Integrate Uniques pallet into thala, rhala and khala runtimes
- Whitelist functions needed in Uniques using BaseFilter
- Integrate RMRK pallet into thala, rhala and khala runtimes
- Whitelist functions needed in RMRK using BaseFilter
- Integrate Phala World Pallet into thala, rhala and khala runtimes
- Run tests to ensure Phala World deployment works
> Integrate Phala World Pallet

- pallets/phala-world/src/incubation.rs
Swap the `(collectionId, nftId)` key1 w/ `eraId` key2. Helps with generating a script to get the top 10 fed Origin of Shells per Era.
> Swap key1 and key2 in OriginOfShellFoodStats

- pallets/assets-registry/Cargo.toml
- pallets/assets-registry/src/lib.rs
- pallets/assets-registry/src/migration.rs
- pallets/assets-registry/src/mock.rs
- pallets/subbridge/src/chainbridge.rs
- pallets/subbridge/src/dynamic_trader.rs
- pallets/subbridge/src/fungible_adapter.rs
- pallets/subbridge/src/helper.rs
- pallets/subbridge/src/lib.rs
- pallets/subbridge/src/migration.rs
- pallets/subbridge/src/mock/para.rs
- pallets/subbridge/src/traits.rs
- pallets/subbridge/src/xcmbridge.rs
- pallets/subbridge/src/xtransfer.rs
- runtime/khala/src/constants.rs
- runtime/khala/src/lib.rs
- runtime/khala/src/migrations.rs
- runtime/rhala/src/constants.rs
- runtime/rhala/src/lib.rs
- runtime/rhala/src/migrations.rs
- runtime/thala/src/constants.rs
- runtime/thala/src/lib.rs
- scripts/js/setup_subbridge.js
- scripts/try-runtime.sh
The origin [PR](https://github.com/Phala-Network/khala-parachain/pull/92) to implement dynamic trader is not compatible with the new SubBridge code, so I picked those stuff to a new PR.
With the dynamic trader introduced, an execution price would be given when registering a new asset. The execution price indicates how much that asset needs to pay per second on our network when buying the resource, which has the same meaning as the returned value of [pha_per_second()](https://github.com/Phala-Network/khala-parachain/blob/12d76b52cf90084a742618aee36b95893327b06a/runtime/khala/src/constants.rs#L73).
This PR would contain storage migration on pallet `chainbridge` and pallet `assets-registry`. They are:
- Remove the fee scale from `chainbridge::BridgeFee`, every ChainBridge only has a constant …
> SubBridge dynamic trader

- Cargo.lock
- pallets/phala-world/README.md
- pallets/phala-world/src/incubation.rs
- pallets/phala-world/src/nft_sale.rs
- pallets/phala-world/src/tests.rs
- pallets/phala-world/src/traits.rs
- runtime/khala/src/lib.rs
- runtime/rhala/src/lib.rs
- runtime/thala/src/lib.rs
> Phala World Fixes

- pallets/phala-world/src/incubation.rs
- pallets/phala-world/src/mock.rs
- pallets/phala-world/src/nft_sale.rs
- runtime/khala/src/lib.rs
- runtime/rhala/src/lib.rs
- runtime/thala/src/lib.rs
Update Phala World dependencies for `polkadot-v0.9.23`
> Update Phala World deps on polkadot-v0.9.23

- runtime/khala/src/lib.rs
- runtime/rhala/src/lib.rs
- runtime/thala/src/lib.rs
Before this change, local account sends XCM to other parachains maybe get failed because inserted instruction `DescendOrigin` according to the barrier config of dest chain. However if some barrier config missed on dest chain, unexpected thing could happen. So far we havn't see any use case that local user needs send XCM to other parachains, it's ok just disable it.
> Disable local account send xcm

- Cargo.lock
- pallets/phala-world/Cargo.toml
- pallets/phala-world/src/lib.rs
- pallets/phala-world/src/mock.rs
- pallets/phala-world/src/tests.rs
- pallets/phala/Cargo.toml
- runtime/khala/src/lib.rs
- runtime/rhala/src/lib.rs
- runtime/thala/src/lib.rs
A typical Arweave uri required 63 bytes, this PR loosen StringLimit to 128 bytes which give us more room to store metadata uri.
Additionally, clean some compiling warnings
> Loosen StringLimit for unique pallet

- pallets/subbridge/src/xtransfer.rs
Previously we return error `TransactFailed` ambiguously by ignore the returned bridges errors,  which is hard to recognize what error throw by bridges when crosschain transfer failed to execute. Consequently return dispatch error directly can solve portion of this problem. However if both XcmBridge and ChainBridge failed, we will return the last error when iterating all configured bridges. Because we run XcmBridge first, then run ChainBridge according to our runtime definition.
> Return last bridge error when crosschain transfer failed to execute

- runtime/khala/src/lib.rs
- runtime/rhala/src/lib.rs
- runtime/thala/src/lib.rs
Change Phala World costs for creating collection, minting nfts & adding attributes.
> Change costs for Phala World collections & mints

- pallets/phala-world/src/mock.rs
- pallets/phala-world/src/nft_sale.rs
- pallets/phala-world/src/tests.rs
- scripts/js/pw/initKhalaParachain.js
> Clean up warnings & add script for local testnet config for PhalaWorld

- polkadot-launch/package.json
- polkadot-launch/src/rpc.ts
- polkadot-launch/src/runner.ts
- polkadot-launch/src/spec.ts
- polkadot-launch/test/test-utils/providers.ts
- polkadot-launch/test/test-utils/setup-para-tests.ts
- polkadot-launch/test/test-utils/substrate-rpc.ts
- polkadot-launch/tsconfig.json
- polkadot-launch/yarn.lock
- scripts/js/package.json
- scripts/js/yarn.lock
- Upgrade JS dependencies
- Polkadot launch requires adiitional adaption https://github.com/paritytech/polkadot-launch/pull/193
- Tested polkadot-launch
- Only tested insert session key
> Upgrade JS dependencies

- pallets/subbridge/src/chainbridge.rs
With this check, we strictly ask the `dest` location explicitly contains `GeneralKey("cb")`
> Check destnation when extract from MultiLocation

- pallets/phala-world/src/incubation.rs
- pallets/phala-world/src/tests.rs
- pallets/phala-world/src/traits.rs
- scripts/js/pw/startIncubationProcess.js
Last week we redesign the metadata database based on the new designs and add more attributes to support the "dress up" feature in the future.
The incubation process demo script has been updated as well, I'd add sample data for Cyborg, and it should be very close to the final synthesis result. The sample data may be related to #184.
Question: do we need sample data for remain three races? I haven't create those yet.
> Update incubation PartInfo with metadata database update

- scripts/js/pw/khala/khalaApi.js
- scripts/js/pw/package.json
- scripts/js/pw/test/initKhalaParachain.js
- scripts/js/pw/test/simulateNftMarketSales.js
- scripts/js/pw/test/startHatchingOriginOfShells.js
- scripts/js/pw/test/startIncubationProcess.js
- scripts/js/pw/test/startLastDayOfSale.js
- scripts/js/pw/test/startOriginShellPreorderProcess.js
- scripts/js/pw/test/startRareOriginOfShellPurchase.js
- scripts/js/pw/test/startSpiritClaimProcess.js
- scripts/js/pw/test/startWhitelistOriginShellPurchase.js
- scripts/js/pw/util/fetch.js
- scripts/js/pw/util/helpers.js
- scripts/js/pw/util/tx.js
Currently frontend has to execute scripts defined in `./scripts/js/pw/` to setup a local testnet, but these scripts only create a chain state for frontend to manually test. This PR will break this out into parts to allow for setting the local testnet chain state, and execute tests using `chai` and `mocha` to avoid manual tests.
> Automating Test Chain State Scripts & Increase Test Coverage Scenarios

- Cargo.lock
- node/Cargo.toml
- node/src/cli.rs
- node/src/command.rs
- node/src/rpc.rs
- node/src/service/mod.rs
- node/src/service/phala.rs
- node/src/service/shell.rs
- pallets/phala-world/src/incubation.rs
- pallets/phala-world/src/migration.rs
- pallets/phala-world/src/mock.rs
- pallets/phala-world/src/nft_sale.rs
- pallets/phala-world/src/tests.rs
- parachains-common/Cargo.toml
- parachains-common/src/lib.rs
- runtime/khala/src/lib.rs
- runtime/phala/src/lib.rs
- runtime/rhala/src/lib.rs
- runtime/thala/src/lib.rs
- scripts/js/pw/util/fetch.js
Upgrade the PhalaWorld pallet to `polkadot-v0.9.32`
> Update PhalaWorld Pallet to polkadot-v0.9.32

- pallets/phala/src/compute/stake_pool_v2.rs
- runtime/khala/src/lib.rs
- runtime/rhala/src/lib.rs
- runtime/thala/src/lib.rs
we shouldn't check mint_into.'s result, for there are some dust in old storage and can't mint such a small amount, we can just ignore it.
> No check for migration mint_into

- pallets/phala-world/src/incubation.rs
- pallets/phala-world/src/migration.rs
- runtime/khala/src/lib.rs
- runtime/khala/src/migrations.rs
- runtime/rhala/src/lib.rs
- runtime/rhala/src/migrations.rs
- runtime/thala/src/lib.rs
Implement migration for the changes from upstream RMRK pallet to move `CollectionIndex` that was purged from the `RmrkCore` pallet and place it in the `PhalaWorld` pallet as `NextCollectionId` in `pallet_pw_nft_sale`. Next, change would be updating all `Nfts` values to be updated based on the change to the `equipped` field in `NftInfo` from `bool` to `Option<(ResourceId, PartId)>`.
> Add initial migration implementation for updates from RMRK.

- Cargo.lock
- node/Cargo.toml
- runtime/khala/Cargo.toml
- runtime/phala/Cargo.toml
- runtime/phala/src/lib.rs
- runtime/rhala/Cargo.toml
- runtime/rhala/src/lib.rs
- runtime/thala/Cargo.toml
- runtime/thala/src/lib.rs
- No filter for Phala pallets (means all Phala pallet functions will work again)
- Corrected wPHA asset id
- Fix an upstream critical client bug (node will random crash hourly)
- Bump all spec version to 1200, Khala is 1201
> Bump to v0.1.20, spec version 1200 (Khala 1201)

- pallets/phala/src/compute/base_pool.rs
- pallets/phala/src/compute/computation.rs
- pallets/phala/src/compute/stake_pool_v2.rs
- pallets/phala/src/compute/vault.rs
- pallets/phala/src/compute/wrapped_balances.rs
- pallets/phala/src/test.rs
- runtime/khala/src/lib.rs
- runtime/phala/src/lib.rs
- runtime/rhala/src/lib.rs
- runtime/thala/src/lib.rs
**Background**
Current stake pool v2 introduced a lot of mint_nft and burn_nft when merging a user's nfts in a collection, many of them are unnecessary and it leads to storage being overwhelmed on the runtime.
And some of the unused codes are removed in this pr by the way.
**Solutions**
1. Changing the function merge_nfts_for_stakers by reducing burn and mint in unnecessary cases
2. The frontend will show nfts basic information generated on their own instead of using nft-properties in on-chain storages So that we can no longer write these data on-chain.
> Optimization of storage usage in Stakepool v2

- Cargo.lock
- node/src/chain_spec/shell.rs
- runtime/shell/Cargo.toml
- runtime/shell/src/lib.rs
- runtime/shell/src/xcm_config.rs
This PR will add `pallet-xcm` from polkadot into shell runtime, to make shell able to send XCM relay chain (only to relay chain).
> Enable xcm sending in shell

- runtime/rhala/src/lib.rs
This PR is going to fix one of the Sygma configurations in Rhala runtime.
> fix: Register missing extrinsic in rhala runtime

- Cargo.lock
- crates/phala-mq/Cargo.toml
- crates/phala-node-rpc-ext/Cargo.toml
- crates/phala-pallet-common/Cargo.toml
- crates/phala-serde-more/Cargo.toml
- crates/phala-trie-storage/Cargo.toml
- crates/phala-types/Cargo.toml
- node/Cargo.toml
- pallets/assets-registry/Cargo.toml
- pallets/index/Cargo.toml
- pallets/parachain-info/Cargo.toml
- pallets/phala-world/Cargo.toml
- pallets/phala/Cargo.toml
- pallets/phala/mq-runtime-api/Cargo.toml
- pallets/subbridge/Cargo.toml
- parachains-common/Cargo.toml
- polkadot/node/service/Cargo.toml
- runtime/khala/Cargo.toml
- runtime/khala/src/lib.rs
- runtime/phala/Cargo.toml
- runtime/phala/src/lib.rs
- runtime/rhala/Cargo.toml
- runtime/rhala/src/lib.rs
- runtime/shell/Cargo.toml
- runtime/thala/Cargo.toml
- runtime/thala/src/lib.rs
https://github.com/paritytech/polkadot/releases/tag/v0.9.41
This is a client-only release, it should be a hotfix version but upstream make it a minor update, so we follow
It only fixed a few client bugs, with no runtime change
I also bump the version to v0.1.24
> Upgrade to Polkadot v0.9.41

- Cargo.lock
- runtime/rhala/Cargo.toml
- runtime/rhala/src/lib.rs
This PR adds the XCM configs necessary to allow Tinkernet multisigs to transact on Rhala.
Tinkernet multisigs have the following MultiLocation pattern:
```rust
MultiLocation {
parents: _, // ancestry depends on the point of reference. 0 if from parent, 1 if from sibling.
interior: Junctions::X3(
Junction::Parachain(2125), // Tinkernet ParaId in Kusama/Rococo.
Junction::PalletInstance(71), // Pallet INV4, from which the multisigs originate.
Junction::GeneralIndex(_) // Index from which the multisig account is derived.
)
}
```
The following are the configs added by this PR to give the multisigs accounts and origins in Rhala:
```rust
WithComputedOrigin<
AllowTopLevelPaidExecutionFrom<invarch_xcm_builder::TinkernetMultisigMultiLocation>,
UniversalLocation,
ConstU32<8>,
>,
```
This is a …
> Introduce Tinkernet multisig XCM configs

- pallets/subbridge/src/xcmbridge.rs
- pallets/subbridge/src/xtransfer.rs
This PR is going to fix a bug in the XCM message forwarder exists in SubBridge.
When forwarding XCM message from other chains like Ethereum, we hardcode the `proofSize` when constructing the XCM message. In XCM V3, this should be a meaningful value rather than 0. Giving 0 will lead to a `Barrier` error on the dest chain. See this [record](https://astar.subscan.io/extrinsic/4041769-1?event=4041769-5).
> Fix XCM message forward

- node/res/khala.json
This bootnode is not available anymore.
> Removing Dwellir bootnode

- runtime/khala/src/lib.rs
Currently there are 3 invulnerable collators and 4 regular collators (candidates) maintained by Phala team. There is at least one stale collator from community cannot be kicked since currently we requires 5 minimum candidates. We need to change to 4 to allow this stale collator to be kicked out.
However, Polkadot 1.0 changed the behavior so invulnerable collators will also be calculated against the "MinEligibleCollators". So this change is temporarily for v0.1.25.
> Change Khala MinCollatorCandidates to 4

- pallets/phala/src/compute/base_pool.rs
- pallets/phala/src/compute/computation.rs
- pallets/phala/src/compute/vault.rs
- pallets/phala/src/snapshots/phala_pallets__test__vault_force_withdraw_after_3x_grace_period.snap
- pallets/phala/src/snapshots/phala_pallets__test__vault_partial_force_withdraw-2.snap
- pallets/phala/src/snapshots/phala_pallets__test__vault_partial_force_withdraw.snap
- pallets/phala/src/snapshots/phala_pallets__test__withdraw1.snap
- pallets/phala/src/snapshots/phala_pallets__test__withdraw2.snap
- pallets/phala/src/snapshots/phala_pallets__test__withdraw3.snap
- pallets/phala/src/snapshots/phala_pallets__test__withdraw4.snap
- pallets/phala/src/snapshots/phala_pallets__test__withdraw5.snap
- pallets/phala/src/snapshots/phala_pallets__test__withdraw6.snap
- pallets/phala/src/snapshots/phala_pallets__test__withdraw7.snap
- pallets/phala/src/snapshots/phala_pallets__test__withdraw8.snap
- pallets/phala/src/snapshots/phala_pallets__test__withdraw9.snap
- pallets/phala/src/test.rs
PR at phala-blockchain: https://github.com/Phala-Network/phala-blockchain/pull/1420
> Integrate Vault & StakePool improvements

- runtime/khala/src/lib.rs
- runtime/phala/src/lib.rs
* change inDEX pallet admin to a multisig account
* update
> Change inDEX pallet admin to a multisig account (#298)

- runtime/khala/src/lib.rs
- runtime/phala/src/lib.rs
- runtime/rhala/src/lib.rs
- runtime/thala/src/lib.rs
This PR is going to fix the missing of whitelisting sygma percentage fee handler pallet in the call filter along with two other notable changes:
- update sygma admin multisig account on Rhala
- add sygUSD on Rhala
> Whitelist percentage fee handler in call filter

- pallets/index/src/lib.rs
- pallets/index/src/mock.rs
- runtime/khala/src/lib.rs
- runtime/phala/src/lib.rs
- runtime/thala/src/lib.rs
Fee deduction in pallet side was implemented in this PR, and currently, fee reserve account on Khala/Phala was set to inDEX multisig admin account
> Support fee deduction in index pallet

- Cargo.lock
- runtime/khala/src/lib.rs
- runtime/rhala/Cargo.toml
- runtime/rhala/src/lib.rs
This PR adds the common XCM location converter HashedDescription, which is used across the ecosystem, to Khala and Rhala.
For reference, chains using HashedDescription include the [relay chain](https://github.com/polkadot-fellows/runtimes/blob/main/relay/kusama/src/xcm_config.rs#L76) and system parachains like the [Asset Hub](https://github.com/polkadot-fellows/runtimes/blob/main/system-parachains/asset-hubs/asset-hub-kusama/src/xcm_config.rs#L93).
The PR also removes the deprecated TinkernetMultisig configs from Rhala.
- added HashedDescription account converter
- added WithComputedOrigin in XCM barrier
> Add HashedDescription XCM location converter and remove TinkernetMultisig configs

- runtime/khala/src/lib.rs
- runtime/phala/src/lib.rs
- runtime/rhala/src/lib.rs
- runtime/thala/src/lib.rs
This PR will switch the migration account used in the compute pallet to a new account controlled by the Phala team.
> compute: switch migration account

- node/res/khala.json
This PR adds the Helikon boot nodes (through p2p and wss/p2p) to the Khala and Phala chain specifications.
To test the Khala boot node:
```
./khala-node --tmp --chain khala --reserved-only --reserved-nodes "/dns4/boot.helikon.io/tcp/15220/p2p/12D3KooWCJKmxeCcj3mA12N6P63wi1WaziAYsDacV4zBq3G2nHyZ"
./khala-node --tmp --chain khala --reserved-only --reserved-nodes "/dns4/boot.helikon.io/tcp/15224/wss/p2p/12D3KooWCJKmxeCcj3mA12N6P63wi1WaziAYsDacV4zBq3G2nHyZ"
```
To test the Phala boot node:
```
./khala-node --tmp --chain phala --reserved-only --reserved-nodes "/dns4/boot.helikon.io/tcp/15020/p2p/12D3KooWDJqyU5YUQNaQzqmfbPbBAKSF4FFwjaQYC5PreQXE4gRE"
./khala-node --tmp --chain phala --reserved-only --reserved-nodes "/dns4/boot.helikon.io/tcp/15024/wss/p2p/12D3KooWDJqyU5YUQNaQzqmfbPbBAKSF4FFwjaQYC …
```
> Add Helikon boot nodes for Khala and Phala

- .github/workflows/build.yml
- Cargo.lock
- crates/phala-pallet-common/Cargo.toml
- node/Cargo.toml
- pallets/assets-registry/Cargo.toml
- pallets/index/Cargo.toml
- pallets/parachain-info/Cargo.toml
- pallets/phala-world/Cargo.toml
- pallets/subbridge/Cargo.toml
- parachains-common/Cargo.toml
- runtime/khala/Cargo.toml
- runtime/khala/build.rs
- runtime/khala/src/lib.rs
- runtime/phala/Cargo.toml
- runtime/phala/build.rs
- runtime/phala/src/lib.rs
- runtime/rhala/Cargo.toml
- runtime/rhala/build.rs
- runtime/rhala/src/lib.rs
- runtime/shell/Cargo.toml
- runtime/shell/build.rs
- runtime/shell/src/lib.rs
- runtime/thala/Cargo.toml
- runtime/thala/build.rs
- runtime/thala/src/lib.rs
- rust-toolchain.toml
**Feature**
Upgrade khala/phala/thala/rhala runtimes to support Polkadot's new ledger app.
> Enable metadata hash verification
