- Cargo.lock
- polkadot-launch/yarn.lock
- runtime/khala/Cargo.toml
- runtime/khala/src/constants.rs
- runtime/khala/src/lib.rs
From
`Fees of 15.0048 milli PHA will be applied to the submission`
To
`Fees of 1.4943 milli PHA will be applied to the submission`
The key is reduce 10x `TransactionByteFee`
> Reduce fee ~10x

- pallets/bridge/src/lib.rs
- pallets/bridge_transfer/Cargo.toml
- pallets/bridge_transfer/src/lib.rs
- pallets/bridge_transfer/src/mock.rs
- pallets/bridge_transfer/src/tests.rs
- runtime/khala/src/lib.rs
- Port https://github.com/Phala-Network/phala-blockchain/pull/433
- Port https://github.com/Phala-Network/phala-blockchain/pull/444
> Port chainbridge latest changes

- pallets/phala/src/lib.rs
- pallets/phala/src/mock.rs
- pallets/phala/src/mq.rs
- pallets/phala/src/mq/check_seq.rs
- pallets/phala/src/ott.rs
- pallets/phala/src/utils/attestation.rs
- runtime/khala/src/lib.rs
Campanion with https://github.com/Phala-Network/phala-blockchain/pull/481
> Integrate Phala OTT pallet

- Cargo.lock
- node/src/service.rs
- pallets/bridge/Cargo.toml
- pallets/bridge/src/lib.rs
- pallets/bridge_transfer/Cargo.toml
- pallets/parachain-info/Cargo.toml
- runtime/khala/Cargo.toml
- runtime/khala/src/lib.rs
Previously our benchmark build is broken, this PR fiexed compile, although the benchmark will fail
> Fix `cargo build --release --features runtime-benchmarks`

- runtime/khala/src/lib.rs
- Remove OTT pallet
- Enable balance transfer
> Enable transfer

- Cargo.lock
- pallets/xcm-transfer/Cargo.toml
- pallets/xcm-transfer/src/assets.rs
- pallets/xcm-transfer/src/mock/para.rs
- pallets/xcm-transfer/src/mock/relay.rs
- pallets/xcm-transfer/src/xcm_helper.rs
- pallets/xcm-transfer/src/xcm_transfer.rs
- runtime/khala/src/lib.rs
- update xcm to v2
- introduce TypeInfo into xcm pallets
> XCM module update

- node/src/command.rs
Reduced some redundant codes. Maybe more clean or not.
> Refine load_spec

- runtime/khala/src/lib.rs
- runtime/khala/src/migrations.rs
> Add pallet migrations between v0.9.10 and v0.9.13

- Cargo.lock
- node/src/chain_spec/khala.rs
- runtime/khala/Cargo.toml
- runtime/khala/src/lib.rs
- runtime/rhala/src/lib.rs
Stuff to support open HRMP channel with other parachains in Kusama network
> Add polkadot xcm pallet to khala runtime

- Cargo.lock
- node/src/chain_spec/rhala.rs
- runtime/rhala/Cargo.toml
- runtime/rhala/src/lib.rs
Almost same changes with [PR55](https://github.com/Phala-Network/khala-parachain/pull/55)
> Add polkadot xcm pallets to Rhala runtime

- pallets/xtransfer/src/xcm/mock/para.rs
- pallets/xtransfer/src/xcm/xcm_transfer.rs
- runtime/khala/src/constants.rs
- runtime/khala/src/lib.rs
- runtime/thala/src/lib.rs
- enable xcm transfer between parachains
- enable x3 transfer between parachains and EVM solo chains
> Enable xtransfer in khala

- Cargo.lock
- Cargo.toml
- node/Cargo.toml
- node/res/shell_local_genesis_info.json
- node/src/chain_spec/mod.rs
- node/src/chain_spec/shell.rs
- node/src/command.rs
- node/src/service/shell.rs
- polkadot-launch/shell_dev.config.json
- runtime/shell/Cargo.toml
- runtime/shell/build.rs
- runtime/shell/src/lib.rs
Beware:
- I don't know we should handle <https://github.com/paritytech/cumulus/blob/master/polkadot-parachains/src/service.rs#L936-L954> 
- There's no `sudo` nor `balance` in Shell runtime, though we can integrate them
UPDATE：
- Introduced `sudo`
> Integrate Shell runtime

- pallets/phala-world/src/nft_sale.rs
- pallets/phala-world/src/tests.rs
Fix preorder failure on last day of sale.
> Last Day of Sale Preorder Fix

- pallets/phala-world/src/nft_sale.rs
- pallets/phala-world/src/tests.rs
Add privileged function to add Spirits Metadata before minting.
> Add Spirits Metadata

- runtime/khala/src/lib.rs
- runtime/rhala/src/lib.rs
- runtime/thala/src/lib.rs
Update BaseCallFilter for Uniques Calls
> Update BaseCallFilter for Uniques Calls

- pallets/subbridge/src/xcmbridge.rs
This is a potential best practice to split recipient as non-chain part from destination.
> Fix xcm bridge recipient path

- Cargo.lock
- node/src/chain_spec/phala.rs
- polkadot-launch/phala_acala.config.json
- runtime/phala/Cargo.toml
- runtime/phala/src/constants.rs
- runtime/phala/src/lib.rs
Before SubBridge can actually work, following requirements need to be fullfilled
- Balances transfer is enabled
- ChainBridge is configed
- Whitelist chain(ethereum and moonriver EVM)
- Add relayers
- Set fee for specific chain
- Run chainbridge relayers
-  Send PHA to account `5EYCAe5iixJKLJE5qkFfWJYxWd9ZsoBVKwBaiLrqY98qbmDC` to do assets registry
-  Send or mint PHA to account `5EYCAe5iixJKLJE5vokZcdJwS4ZpFU23Ged95YDBznC789dM` to make PHA chainbridge work
- Phala ChainBridge ChainId is set to 3, ChainBridge relayers should set it properly
> Enable SubBridge on phala network

- Cargo.lock
- crates/phala-mq/Cargo.toml
- crates/phala-node-rpc-ext/Cargo.toml
- crates/phala-serde-more/Cargo.toml
- crates/phala-trie-storage/Cargo.toml
- crates/phala-types/Cargo.toml
- node/Cargo.toml
- pallets/assets-registry/Cargo.toml
- pallets/parachain-info/Cargo.toml
- pallets/phala-world/Cargo.toml
- pallets/phala-world/src/incubation.rs
- pallets/phala-world/src/mock.rs
- pallets/phala-world/src/nft_sale.rs
- pallets/phala/Cargo.toml
- pallets/phala/mq-runtime-api/Cargo.toml
- pallets/subbridge/Cargo.toml
- parachains-common/Cargo.toml
- polkadot/node/service/Cargo.toml
- runtime/khala/Cargo.toml
- runtime/khala/src/lib.rs
- runtime/phala/Cargo.toml
- runtime/rhala/Cargo.toml
- runtime/rhala/src/lib.rs
- runtime/shell/Cargo.toml
- runtime/thala/Cargo.toml
- runtime/thala/src/lib.rs
- substrate/frame/utility/Cargo.toml
> Upgrade to polkadot-v0.9.24 and make changes to Phala World pallet

- pallets/phala/src/registry.rs
- pallets/phala/src/stakepool.rs
https://github.com/Phala-Network/phala-blockchain/pull/835
> Port phala #835

- runtime/khala/src/lib.rs
- runtime/rhala/src/lib.rs
- runtime/thala/src/lib.rs
Add Calls for  `add_basic_resource`, `accept_resource`, `remove_resource` & `accept_resource_removal` from  `pallet_rmrk_core`.
> Add Calls for adding and accepting basic resources

- .github/workflows/build.yml
- .gitignore
Though we finally make the CI happy, I still see warnings, let's try more tuning
> chore: tune GH Actions again

- scripts/js/xtransfer.js
- Transfer GLMR&PHA from Moonbeam to Phala
- Transfer PHA from Ethereum to Phala
> Some example code of new token transfer 

- pallets/phala/src/stakepool.rs
Forbid worker to be removed when it is not reclaimed yet.
> Restrict remove_worker limitation

- pallets/phala/src/compute/base_pool.rs
- pallets/phala/src/compute/computation.rs
- pallets/phala/src/compute/mod.rs
- pallets/phala/src/compute/pawn_shop.rs
- pallets/phala/src/compute/pool_proxy.rs
- pallets/phala/src/compute/stake_pool_v2.rs
- pallets/phala/src/compute/vault.rs
- pallets/phala/src/fat.rs
- pallets/phala/src/fat_tokenomic/tests/mock.rs
- pallets/phala/src/lib.rs
- pallets/phala/src/migrations/mod.rs
- pallets/phala/src/mock.rs
- pallets/phala/src/registry.rs
- pallets/phala/src/stake_pool.rs
- pallets/phala/src/test.rs
- pallets/phala/src/utils/attestation.rs
- pallets/phala/src/utils/attestation_legacy.rs
> Push for updating migrations

- Cargo.lock
- node/Cargo.toml
- runtime/khala/Cargo.toml
- runtime/khala/src/lib.rs
- runtime/phala/Cargo.toml
- runtime/phala/src/lib.rs
- runtime/rhala/Cargo.toml
- runtime/rhala/src/lib.rs
- runtime/thala/Cargo.toml
- runtime/thala/src/lib.rs
@HashWarlock said PW team requires a new Runtime version for new incubation logic
> Bump to v0.1.19-2 and runtime 1192

- pallets/phala/src/mining.rs
https://github.com/Phala-Network/phala-blockchain/pull/1046
https://github.com/Phala-Network/phala-blockchain/pull/1047
> Port Phala PR #1046 & #1047

- runtime/khala/src/lib.rs
> Add filters for migrations

- runtime/khala/src/lib.rs
> post migration

- pallets/phala/src/compute/stake_pool_v2.rs
- runtime/khala/src/lib.rs
> Update to release 1200

- runtime/khala/src/lib.rs
> Update to release 1201

- runtime/khala/src/lib.rs
> change cooldown period

- crates/phala-types/src/lib.rs
- pallets/phala/src/compute/base_pool.rs
- pallets/phala/src/compute/stake_pool_v2.rs
- pallets/phala/src/compute/wrapped_balances.rs
- pallets/phala/src/fat_tokenomic/tests/mock.rs
- pallets/phala/src/mock.rs
- pallets/phala/src/registry.rs
- pallets/phala/src/test.rs
- runtime/khala/src/lib.rs
- runtime/rhala/src/lib.rs
- runtime/thala/src/lib.rs
Sync Phala changes to https://github.com/Phala-Network/phala-blockchain/commit/c83ee94e4f4f415c2933235fcbd758740430ed56
- Fix unwrap and lock_account
- Fix a typo
> Sync Phala changes to c83ee94, fix unwrap and lock_account

- pallets/phala/src/compute/base_pool.rs
- pallets/phala/src/compute/stake_pool_v2.rs
- runtime/khala/src/lib.rs
- runtime/rhala/src/lib.rs
- runtime/thala/src/lib.rs
Changes:
- https://github.com/Phala-Network/phala-blockchain/pull/1086
- Also bump spec version to 1203
> Sync phala for rmrk problem

- pallets/phala/src/compute/base_pool.rs
- runtime/khala/src/lib.rs
- runtime/rhala/src/lib.rs
- runtime/thala/src/lib.rs
- https://github.com/Phala-Network/phala-blockchain/pull/1089
- Bump Khala, Rhala, Thala spec version to 1204
> Sync phala for rmrk problem 2

- pallets/phala/src/compute/base_pool.rs
- pallets/phala/src/utils/balance_convert.rs
> fix vault-3474

- pallets/phala/src/compute/vault.rs
> merge for vault owner

- runtime/khala/Cargo.toml
- runtime/khala/src/lib.rs
- runtime/phala/Cargo.toml
- runtime/phala/src/lib.rs
> Enable pallet index in khala&phala

- runtime/phala/src/lib.rs
- runtime/phala/src/msg_routing.rs
Forbid phat pallets for phala runtime.
> forbid phat pallets

- runtime/phala/src/lib.rs
- Enable all Phala pallets' calls
- Bump Phala runtime version to 1243
> Enable phala on phala

- Cargo.lock
- Cargo.toml
- node/Cargo.toml
- substrate/client/network/sync/Cargo.toml
- substrate/client/network/sync/build.rs
- substrate/client/network/sync/src/block_request_handler.rs
- substrate/client/network/sync/src/blocks.rs
- substrate/client/network/sync/src/engine.rs
- substrate/client/network/sync/src/extra_requests.rs
- substrate/client/network/sync/src/lib.rs
- substrate/client/network/sync/src/mock.rs
- substrate/client/network/sync/src/schema.rs
- substrate/client/network/sync/src/schema/api.v1.proto
- substrate/client/network/sync/src/service/chain_sync.rs
- substrate/client/network/sync/src/service/mock.rs
- substrate/client/network/sync/src/service/mod.rs
- substrate/client/network/sync/src/service/network.rs
- substrate/client/network/sync/src/state.rs
- substrate/client/network/sync/src/state_request_handler.rs
- substrate/client/network/sync/src/warp.rs
- substrate/client/network/sync/src/warp_request_handler.rs
> Backport Substrate #13829 and #13941

- Cargo.lock
- node/Cargo.toml
- node/src/service/mod.rs
Note: Without modify Substrate, it's hard to make it configuration, so we hard code for now
> Integrate sc-storage-monitor

- polkadot-launch/rhala_shibuya.config.json
- polkadot-launch/src/spawn.ts
> Add rhala&shibuya config

- Cargo.lock
- Cargo.toml
- polkadot/node/service/src/lib.rs
- substrate/client/consensus/grandpa/Cargo.toml
- substrate/client/consensus/grandpa/README.md
- substrate/client/consensus/grandpa/src/authorities.rs
- substrate/client/consensus/grandpa/src/aux_schema.rs
- substrate/client/consensus/grandpa/src/communication/gossip.rs
- substrate/client/consensus/grandpa/src/communication/mod.rs
- substrate/client/consensus/grandpa/src/communication/periodic.rs
- substrate/client/consensus/grandpa/src/communication/tests.rs
- substrate/client/consensus/grandpa/src/environment.rs
- substrate/client/consensus/grandpa/src/finality_proof.rs
- substrate/client/consensus/grandpa/src/import.rs
- substrate/client/consensus/grandpa/src/justification.rs
- substrate/client/consensus/grandpa/src/lib.rs
- substrate/client/consensus/grandpa/src/notification.rs
- substrate/client/consensus/grandpa/src/observer.rs
- substrate/client/consensus/grandpa/src/tests.rs
- substrate/client/consensus/grandpa/src/until_imported.rs
- substrate/client/consensus/grandpa/src/voting_rule.rs
- substrate/client/consensus/grandpa/src/warp_proof.rs
https://github.com/paritytech/substrate/pull/14423#issuecomment-1633837906
> Backport https://github.com/paritytech/substrate/pull/14423

- pallets/subbridge/src/sygma_wrapper.rs
Return `None` if given DomainID in GeneralIndex more than 255
> Fix sygma bridge DomainID overflow

- Cargo.lock
This PR is going to bring the [deposit nonce fix PR](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/6652fe412c86b35a9a89175fcc52a035b460691c) from Sygma pallets to solve the overflow problem happened on Phala network and potentially on Khala network in the future
> Bring sygma deposit nonce fix
